services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
  db:
    image: ankane/pgvector
    restart: unless-stopped
    volumes:
      - ${PWD}/db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
  py:
    image: python:3.8
    command: tail -f /dev/null
    restart: unless-stopped
    # give AMD gpu access
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${PWD}/py:/app
